### ISSUE TITLE
Перевести Telegram парсер на httpx/другой асинхронный фреймворк

### ISSUE THREAD

**Issue by VeryBigSad** [ffmemes/ff-backend#2]
В данный момент тг-парсер в `src/storage/parsers/snscrape/modules/telegram.py` использует `requests`.
Стоит переписать его с библиотекой `httpx`/`aiohttp`, для того, чтобы модуль парсера стал асинхронным

**Comment by SUPERustam** [comment]
Можно также использовать https://github.com/MagicStack/uvloop вместо asyncio.run()

**Comment by VeryBigSad** [comment]
> Можно также использовать https://github.com/MagicStack/uvloop вместо asyncio.run()

#4

**Comment by aleksspevak** [comment]
Перешли на httpx, [коммит](https://github.com/ffmemes/ff-backend/commit/d491ed39ed0bc05639e8df8591a9b9e2307433ce)
